Feat timeline
antvis/GUI pull request #129
Opened 2022-03-07 12:17 UTC by rainy-25Ghz

slideraxis拖拽性能问题。
slideraxis的shape层级：
- ticks
- backgroundShape
  - selectionShape
    - startHandleShape
    - endHandleShape

2022-03-11 04:07 UTC, visiky commented on src/ui/timeline/cellaxis.ts
> +    console.log(positionX, x, left, cellWidth + cellGap);
log

2022-03-11 04:07 UTC, visiky commented on src/ui/timeline/cellaxis.ts
> +    let cellIdx = Math.floor((positionX - x - left) / (cellWidth + cellGap));
如果是这么计算的话，是不是 3.8 也属于 3 的区间了？`Math.round` 如何呢？

2022-03-11 04:07 UTC, visiky commented on src/ui/timeline/cellaxis.ts
> +  }
如果两段结合起来的话，是不是下面这段代码也可以代表呢？
```ts
createSelection() {
  const { cellStyle, selection = [], single } = this.attributes;
  const { selected: selectedStyle } = cellStyle;

  let [startIdx = 0, endIdx = (single ? startIdx : 1)] = selection;
  startIdx = this.timeIndexMap.get(startIdx);
  endIdx = this.timeIndexMap.get(endIdx);
  for (let i = startIdx; i <= endIdx; i += 1) {
    this.cellShapes[i].attr({
      ...selectedStyle,
    });
  }
}
```

2022-03-11 04:53 UTC, visiky commented on src/ui/timeline/slideraxis.ts
> +    this.bindEvents();
看起来直接调用 this.update 就行了

2022-03-11 05:10 UTC, rainy-25Ghz commented on src/ui/timeline/slideraxis.ts
> +    this.bindEvents();
update需要cfg参数

2022-03-11 08:26 UTC, rainy-25Ghz commented on src/ui/timeline/cellaxis.ts
> +    let cellIdx = Math.floor((positionX - x - left) / (cellWidth + cellGap));
![image](https://user-images.githubusercontent.com/37009709/157830125-f89eec55-b2a7-4d15-a405-6ec051e723e5.png)
可以试想一下这种情况，点击后如果四舍五入算出来的idx就是1，显然不正确。

2022-03-15 12:31 UTC, visiky commented
自查表：
- [ ] demo
- [ ] 单测

2022-03-22 07:32 UTC, rainy-25Ghz commented
todo 
- [] 支持在播放时切换单一时间，不暂停。
- [] 支持高度参数，支持溢出滚动

2022-03-22 13:54 UTC, visiky requested changes

2022-03-22 13:54 UTC, visiky commented on src/ui/tooltip/index.ts
> +  public showTip() {
应该是 `show`

2022-03-22 13:54 UTC, visiky commented on src/ui/tooltip/index.ts
> +  public hideTip() {
应该是 `hide`

2022-03-28 13:25 UTC, closed without merging